/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        "status": string;
        "text": string;
    }
    interface ImageComponent {
        "image": {legend: string, image:string};
    }
    interface ParagraphText {
        "size": string;
        "text": string;
    }
    interface SearchComponent {
    }
    interface SwitchComponent {
    }
}
export interface SearchComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchComponentElement;
}
export interface SwitchComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSwitchComponentElement;
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLImageComponentElement extends Components.ImageComponent, HTMLStencilElement {
    }
    var HTMLImageComponentElement: {
        prototype: HTMLImageComponentElement;
        new (): HTMLImageComponentElement;
    };
    interface HTMLParagraphTextElement extends Components.ParagraphText, HTMLStencilElement {
    }
    var HTMLParagraphTextElement: {
        prototype: HTMLParagraphTextElement;
        new (): HTMLParagraphTextElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLSwitchComponentElement extends Components.SwitchComponent, HTMLStencilElement {
    }
    var HTMLSwitchComponentElement: {
        prototype: HTMLSwitchComponentElement;
        new (): HTMLSwitchComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "image-component": HTMLImageComponentElement;
        "paragraph-text": HTMLParagraphTextElement;
        "search-component": HTMLSearchComponentElement;
        "switch-component": HTMLSwitchComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "status"?: string;
        "text"?: string;
    }
    interface ImageComponent {
        "image"?: {legend: string, image:string};
    }
    interface ParagraphText {
        "size"?: string;
        "text"?: string;
    }
    interface SearchComponent {
        "onInputCompleted"?: (event: SearchComponentCustomEvent<any>) => void;
    }
    interface SwitchComponent {
        "onChangeTheme"?: (event: SwitchComponentCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "image-component": ImageComponent;
        "paragraph-text": ParagraphText;
        "search-component": SearchComponent;
        "switch-component": SwitchComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "image-component": LocalJSX.ImageComponent & JSXBase.HTMLAttributes<HTMLImageComponentElement>;
            "paragraph-text": LocalJSX.ParagraphText & JSXBase.HTMLAttributes<HTMLParagraphTextElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
            "switch-component": LocalJSX.SwitchComponent & JSXBase.HTMLAttributes<HTMLSwitchComponentElement>;
        }
    }
}
