/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        "status": string;
        "text": string;
    }
    interface ImageComponent {
        "image": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ParagraphText {
        "size": string;
        "text": string;
    }
    interface SearchComponent {
    }
    interface SwitchComponent {
    }
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLImageComponentElement extends Components.ImageComponent, HTMLStencilElement {
    }
    var HTMLImageComponentElement: {
        prototype: HTMLImageComponentElement;
        new (): HTMLImageComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParagraphTextElement extends Components.ParagraphText, HTMLStencilElement {
    }
    var HTMLParagraphTextElement: {
        prototype: HTMLParagraphTextElement;
        new (): HTMLParagraphTextElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLSwitchComponentElement extends Components.SwitchComponent, HTMLStencilElement {
    }
    var HTMLSwitchComponentElement: {
        prototype: HTMLSwitchComponentElement;
        new (): HTMLSwitchComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "image-component": HTMLImageComponentElement;
        "my-component": HTMLMyComponentElement;
        "paragraph-text": HTMLParagraphTextElement;
        "search-component": HTMLSearchComponentElement;
        "switch-component": HTMLSwitchComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "status"?: string;
        "text"?: string;
    }
    interface ImageComponent {
        "image"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParagraphText {
        "size"?: string;
        "text"?: string;
    }
    interface SearchComponent {
    }
    interface SwitchComponent {
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "image-component": ImageComponent;
        "my-component": MyComponent;
        "paragraph-text": ParagraphText;
        "search-component": SearchComponent;
        "switch-component": SwitchComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "image-component": LocalJSX.ImageComponent & JSXBase.HTMLAttributes<HTMLImageComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "paragraph-text": LocalJSX.ParagraphText & JSXBase.HTMLAttributes<HTMLParagraphTextElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
            "switch-component": LocalJSX.SwitchComponent & JSXBase.HTMLAttributes<HTMLSwitchComponentElement>;
        }
    }
}
